"""AI Office Tools — email, telegram, web browser."""

from tools.email_sender import (
    send_email,
    send_bulk_email,
    send_from_template,
    send_drip_sequence,
    send_daily_report_email,
    get_email_stats,
    get_send_log,
    list_templates,
    TEMPLATES,
)
from tools.telegram_bot import (
    send_message as telegram_send_message,
    send_html_message as telegram_send_html,
    send_alert as telegram_send_alert,
    send_agent_update as telegram_agent_update,
    send_metric_report as telegram_metric_report,
    send_daily_report,
    send_cycle_summary,
    send_with_buttons,
    get_updates as telegram_get_updates,
    process_commands as telegram_process_commands,
    get_bot_info as telegram_bot_info,
    get_telegram_stats,
    get_message_log as telegram_message_log,
)
from tools.web_browser import (
    web_search,
    multi_search,
    fetch_page,
    fetch_page_structured,
    fetch_github_readme,
    fetch_github_repo_info,
    fetch_github_issues,
    extract_emails_from_page,
    extract_social_links,
    research_competitor,
    research_topic,
    fetch_rss,
    monitor_news,
    analyze_seo,
    search_product_hunt,
    detect_technologies,
    get_browser_stats,
    get_research_log,
    clear_cache,
)

__all__ = [
    # Email
    "send_email",
    "send_bulk_email",
    "send_from_template",
    "send_drip_sequence",
    "send_daily_report_email",
    "get_email_stats",
    "get_send_log",
    "list_templates",
    "TEMPLATES",
    # Telegram
    "telegram_send_message",
    "telegram_send_html",
    "telegram_send_alert",
    "telegram_agent_update",
    "telegram_metric_report",
    "send_daily_report",
    "send_cycle_summary",
    "send_with_buttons",
    "telegram_get_updates",
    "telegram_process_commands",
    "telegram_bot_info",
    "get_telegram_stats",
    "telegram_message_log",
    # Web Browser
    "web_search",
    "multi_search",
    "fetch_page",
    "fetch_page_structured",
    "fetch_github_readme",
    "fetch_github_repo_info",
    "fetch_github_issues",
    "extract_emails_from_page",
    "extract_social_links",
    "research_competitor",
    "research_topic",
    "fetch_rss",
    "monitor_news",
    "analyze_seo",
    "search_product_hunt",
    "detect_technologies",
    "get_browser_stats",
    "get_research_log",
    "clear_cache",
]